=== thuyle2000/2303.sem2/xml/src/d02_product.xsd
<?xml version="1.0"?>
<!--
ho so chua danh sach san pham
moi sp, 
	co thuoc tinh : maso id, trangthai 
        co noi dung: tensp, don-gia, soluongtk, loaisp
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="product-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" minOccurs="1" maxOccurs="3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal" />
                            <xs:element name="qoh" type="xs:positiveInteger" />
                            <xs:element name="cat" type="xs:string" />
                        </xs:sequence>
                        
                        <xs:attribute name="id" type="xs:string" />
                        <xs:attribute name="status" type="xs:boolean" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== thuyle2000/2303.sem2/xml/src/d02_product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<product-list
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='d02_product.xsd'>
    <product id="P01" status="true">
        <name>coca cola</name>
        <price>8.99</price>
        <qoh>12</qoh>
        <cat>Food</cat>
    </product>
    
    <product id="P02" status="false">
        <name>cha ca muc</name>
        <price>10</price>
        <qoh>5</qoh>
        <cat>Food</cat>
    </product>

</product-list>
